const ProjectsData = [
  //mine
  {
    id: 10,
    title: "Distributed-Logging-System",
    description: "Streamlined processes for collecting and analysing logs generated by 3 microservices in healthcare domain",
    image: "/images/projects/Distrib_log.png",
    tag: ["Big Data", "All"],
    tech:["Big Data"  ,"Kafka","Fluentd","Elastic Search" ],
    gitUrl: "https://github.com/diishanbhag/Distributed-Logging-System",
    previewUrl: "https://github.com/diishanbhag/Distributed-Logging-System/blob/main/README.md",
  },

  //mine
  {
    id: 14,
    title: "Frog game AI",
    description: " AI for Frog Jump  game",
    image: "/images/projects/froggy.png",
    tag: ["All", "Machine Learning"],
    tech:["Reinforcement Learning"],
    gitUrl: "https://github.com/diishanbhag/Froggy",
    previewUrl: "https://github.com/diishanbhag/Froggy/blob/main/README.md",
  },
  //mine
  {
    id: 11,
    title: "Micro Class Plane",
    description: "Built a micro class plane for the SAE DDC 24 and won AIR 4 overall and AIR 2 under best presentation",
    image: "/images/projects/indi.png",
    tag: ["All", "Other"],
    tech:["Aero",],
    gitUrl: "",
    previewUrl: "",
  },
  //mine
  {
    id: 12,
    title: "Another Kubernetes",
    description: "Distributed file orchestration and synchronization with ",
    image: "/images/projects/kuber.png",
    tag: ["All", "Big Data"],
    tech:["Computer Vision" ,"Mediapipe"],
    gitUrl: "https://github.com/diishanbhag/Distributed-file-orchestration-and-synchronization",
    previewUrl: "https://github.com/diishanbhag/Distributed-file-orchestration-and-synchronization/blob/main/README%20copy.md",
  },
  //mine
  {
    id: 13,
    title: "Tourism Finder",
    description: " Built an Intelligent Proximity-Based Tourism Recommendation System with NLP-Driven Summarization and Multilingual Support ",
    image: "/images/projects/tourism.png",
    tag: [ "All","Machine Learning","Web Dev"],
    tech:["Recommender System" ,"BERT","Content Based Filtering" ],
    gitUrl: "https://github.com/diishanbhag/tourism-finder",
    previewUrl: "https://github.com/diishanbhag/tourism-finder/blob/main/README.md",
  },

  {
    id: 15,
    title: "AI powered Budget app",
    description: "Developed a full-stack budget app with a chatbot to track transactions, set savings goals, and manage budgets with AI-driven categorization . ",
    image: "/images/projects/budget.png",
    tag: [ "All","Web Dev","Machine Learning"],
    tech:["Deep Learning" ,"CNN"],
    gitUrl: "https://www.kaggle.com/code/kumarsampurn/music-genre-classifier",
    previewUrl: "https://www.kaggle.com/code/kumarsampurn/music-genre-classifier",
  },

  {
    id: 16,
    title: "Vehicle detection",
    description: "Detection of vehicle overspeeding and lane change for trucks for a camera footage ",
    image: "/images/projects/audio.gif",
    tag: [ "Machine Learning"],
    tech:["Yolov8" ,"CNN"],
    gitUrl: "",
    previewUrl: "",
  },






  {
    id: 17,
    title: "OffTheShelf",
    description: "Lead clothing designer for the brand OfftheShelf ",
    image: "/images/art/offtheshelf.jpeg",
    tag: [ "Art and Design"],
    tech:[],
    gitUrl: "",
    previewUrl: "https://www.instagram.com/offtheshelf_clothing/",
  }
  
  ];

  export default ProjectsData;